### ISSUE TITLE
运行gazebo机器人倒下，无法站起来

### ISSUE THREAD

**Issue by opan08** [AgibotTech/agibot_x1_infer#10]
请问一下，为什么我运行gazebo仿真，机器人是倒下的？而且无法站起来。谢谢解答。

![image](https://github.com/user-attachments/assets/b4d1d71a-e598-407b-925b-549b3a596632)

**Comment by ckji** [comment]
ros2 service call /reset_world std_srvs/srv/Empty 试了吗

**Comment by opan08** [comment]
> ros2 service call /reset_world std_srvs/srv/Empty 试了吗

问题解决，谢谢！
