### ISSUE TITLE
SetImuData：咨询一个关于线程安全的疑问

### ISSUE THREAD

**Issue by tokamakz** [AgibotTech/agibot_x1_infer#3]
`SetImuData`是在`Subscribe`的回调函数中执行，回调函数是运行在`Subscribe`内部线程。
https://github.com/AgibotTech/agibot_x1_infer/blob/09b17bdec73b0a4829d56b786f75092b6a2ebbad/src/module/rl_control_module/rl_control_module.cc#L160-L163

然而`imu_data_`是在`RlControlModule::MainLoop`线程中使用：
https://github.com/AgibotTech/agibot_x1_infer/blob/09b17bdec73b0a4829d56b786f75092b6a2ebbad/src/module/rl_control_module/rl_controller.cc#L66

所以`imu_data_ = imu_data`的数据拷贝没有加锁，是不是线程不安全的行为？

(对AimRT的运行机制原理还不是很熟悉，请指教)

**Comment by caiwei2333** [comment]
感谢你提出的问题！经过仔细检查，我们确认了问题的来源，不同线程访问了rl_controller_，这是由于我们对 [aimrt] 的部分实现存在误解。感谢你帮助我们发现了这一点！
我们会尽快修正代码，也非常感谢你对项目的支持。如果有其他问题，欢迎随时反馈！
请阅读：
https://docs.aimrt.org/tutorials/interface_cpp/channel.html#subscribe
https://docs.aimrt.org/tutorials/interface_cpp/executor.html#id6

![20241025-162649](https://github.com/user-attachments/assets/fe855e37-0a38-43df-aae4-78dc5045b32a)

可以了解运行机制原理这方面内容

**Comment by tokamakz** [comment]
嗯，了解了。

**Comment by caiwei2333** [comment]
提交[https://github.com/AgibotTech/agibot_x1_infer/commit/831eb0d53b4633d26b71883c0e8d070a5ec20884](url)已添加读写锁

**Comment by caiwei2333** [comment]
已修复该问题，[831eb0d](https://github.com/AgibotTech/agibot_x1_infer/commit/831eb0d53b4633d26b71883c0e8d070a5ec20884)
