### ISSUE TITLE
libstdc++.so.6链接错误：version `GLIBCXX_3.4.32' not found，是否考虑更新依赖安装文档

### ISSUE THREAD

**Issue by DongPF1992** [AgibotTech/agibot_x1_infer#4]
操作系统：ubuntu 22.04.05 LTS
cmake版本：3.30.5（手动安装）
gcc版本：11.4.0

运行报错：
AimRT run with exception and exit. Load dynamic lib failed, lib path ./libpkg1.so, error info /lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.32' not found (required by xxx用户目录xxx/agibot_x1_infer/build/install/lib/libxyber_controller.so)`

参考解决方案：
[https://stackoverflow.com/questions/76974555/glibcxx-3-4-32-not-found-error-at-runtime-gcc-13-2-0，即](https://stackoverflow.com/questions/76974555/glibcxx-3-4-32-not-found-error-at-runtime-gcc-13-2-0%EF%BC%8C%E5%8D%B3)

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install --only-upgrade libstdc++6

**Comment by CTGUMARK** [comment]
是的  我也遇到到了，也是使用该方法解决的

**Comment by RichieStyle** [comment]
感谢您的关注
libxyber_controller.so 是用GCC13编译的，依赖文档里面并没有声明，十分抱歉
提交 ab77b32 已经更换为 GCC11 编译版本

**Comment by DongPF1992** [comment]
已修复
