### ISSUE TITLE
How should I adjust init standing pose? Can't do sim as init pose seems to crumble.

### ISSUE THREAD

**Issue by fwd4** [AgibotTech/agibot_x1_infer#8]
Init pose like:
![image](https://github.com/user-attachments/assets/97f55c00-790b-4bd3-a202-006a7295dac6)

After reset, it fell down like this, make its knee joint angle even more weird.
![image](https://github.com/user-attachments/assets/1f0ea2f4-ed5c-4fa5-baa8-038e4a7d650e)

Multiple resets makes it even worse:
![image](https://github.com/user-attachments/assets/29fabe89-919d-45e1-a38c-93a53738792f)

**Comment by caiwei2333** [comment]
To help resolve the compilation problem more effectively, we need some additional information. Please provide the following environment and log details.
1. `Logs`: Detailed log outputs for `aimrt` and `gazebo`, and attach the relevant error logs to this issue.
2. `Performance`: Simulation time in `gazebo`, along with the frequency of sensors and actuators, such as `/joint_states`, `/imu/data`, and `/effort_controller/commands`.

**Comment by fwd4** [comment]
I'm attaching aimrt/gazebo logs as below:
[x1_rl_ctrl.log](https://github.com/user-attachments/files/17551100/x1_rl_ctrl.log)
[x1_gazebo.log](https://github.com/user-attachments/files/17551101/x1_gazebo.log)

I'm very new to this and don't quite understand about Performance part, how should I get those?

**Comment by caiwei2333** [comment]
Slove this problem:
`apt install ros-$ROS_DISTRO-ros2-controllers`

1. Check topic:
`ros2 topic hz -w 1000 <topic>`
``ros2 topic echo <topic>`
[ros2 topic](https://docs.ros.org/en/foxy/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-
Topics.html)
2. Check simulation time:
![image](https://github.com/user-attachments/assets/b10166db-4d5d-4297-bab0-70724245387c)

**Comment by fwd4** [comment]
very nice! problem solved
